name: chuck_example
version: 1.0.0+1
publish_to: "none"
description: "Demonstrates how to use the Chuck Interceptor plugin."

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  chuck_interceptor:
    path: ../

dev_dependencies:
  analysis_lints: ^1.0.2

flutter:

  uses-material-design: true
